#!/bin/bash

set -e

# Add the docker host IP as seen from the container. Requests from this IP will be allowed by better_errors.
export DOCKER_HOST_IP=`/sbin/ip -4 route list match 0/0 | awk '{ print $3 }' | head -n 1`

echo "⚙️ Testing DB connection"
timeout 300s /bin/waitfortcp "${RAILS_DB_HOST-db}" "${RAILS_DB_PORT-3306}"
echo "✅ DB is ready"

echo "⚙️ Performing migrations"
bundle exec rake db:migrate wagon:migrate
echo "✅ Migrations done"

if [ ! -f /seed/done ]; then
  echo "⚙️ Seeding DB and resetting root user password"
  bundle exec rake db:seed wagon:seed && date > /seed/done
  echo 'p=Person.first; p.update!(password: "hito42bito", first_name: "Puzzle", last_name: "ITC", birthday: "1999-09-09"); "You can now login under http://localhost:3000 as #{p.email} with the password '"'"'hito42bito'"'"'"' | rails c
  echo "✅ Seeding and password reset done"
else
  echo "↪️ Skipping seeding because already done on $(cat /seed/done)"
fi


echo "➡️ Handing control over to '$*''"

exec bundle exec "$@"
