name: Check PR
on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start hitobito
      run: docker-compose up -d app
    - name: Run cypress
      uses: cypress-io/github-action@v1
      with:
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 600
    - name: Clean up docker
      run: docker-compose down