name: Check PR
on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start hitobito
      run: docker-compose up -d app
    - name: Run cypress
      run: docker-compose run --rm cypress
    - name: Clean up docker
      run: docker-compose down