name: Check PR

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: hitobito/development
        path: development
    - uses: actions/checkout@v2
      with:
        repository: hitobito/hitobito
        path: development/app/hitobito
    - uses: actions/checkout@v2
      with:
        repository: hitobito/hitobito_youth
        path: development/app/hitobito_youth
    - uses: actions/checkout@v2
      with:
        repository: hitobito/hitobito_pbs
        path: development/app/hitobito_pbs
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Pull images
      run: docker-compose pull --include-deps --quiet rails worker
      continue-on-error: true
    - name: Create Cache Volumes
      run: |
        docker volume create hitobito_bundle
        docker volume create hitobito_yarn_cache
    - name: Start hitobito
      run: |
        export RAILS_UID=$(id -u)
        docker-compose up -d rails worker
    - name: Run cypress
      uses: cypress-io/github-action@v2
      with:
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 600
    - name: Stop hitobito
      if: always()
      run: docker-compose down
    # after the test run completes
    # store videos and any screenshots
    # NOTE: screenshots will be generated only if E2E test failed
    # thus we store screenshots only on failures
    # Alternative: create and commit an empty cypress/screenshots folder
    # to always have something to upload
    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Screenshots
        path: cypress/screenshots
    # Test run video was always captured, so this action uses "always()" condition
    - name: Upload videos
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Videos
        path: cypress/videos      